import PropTypes from 'prop-types';
import SEO from '../utils/SEO.jsx';

const PrivacyPolicy = () => {
  const seoData = {
    title: 'Privacy Policy - MyConverterTool',
    description: 'Read how MyConverterTool handles files, account data, cookies, analytics, and advertising technologies.',
    canonicalUrl: '/privacy-policy',
    ogType: 'website',
  };

  return (
    <div className="pb-24">
      <SEO seoData={seoData} />
      <LegalHeader title="Privacy Policy" subtitle="How MyConverterTool handles your data, files, cookies, and advertising signals." />

      <LegalSection title="Information We Collect">
        <p>We collect information you provide directly, such as account details, profile information, contact messages, uploaded files, and files generated by the tools you choose to use.</p>
        <p>We also collect basic technical information such as device type, browser, pages visited, approximate location from IP address, log data, and diagnostic events needed to keep the service secure and reliable.</p>
      </LegalSection>

      <LegalSection title="Files and Tool Usage">
        <p>Files are processed to provide the requested conversion, editing, formatting, or generation feature. We do not sell uploaded files. Temporary processing files may be stored briefly for delivery, troubleshooting, abuse prevention, and system reliability, then removed according to operational cleanup routines.</p>
        <p>Do not upload sensitive, confidential, or regulated information unless you are comfortable processing it through an online tool.</p>
      </LegalSection>

      <LegalSection title="Cookies, Analytics, and Advertising">
        <p>MyConverterTool may use cookies, local storage, analytics tools, and similar technologies to remember preferences, maintain sessions, understand site performance, prevent abuse, and improve the service.</p>
        <p>When Google AdSense is enabled, Google and its partners may use cookies or similar technologies to serve and measure ads. These technologies may use visits to this and other websites to personalize ads where allowed by law and user settings.</p>
        <p>You can manage Google ad personalization from your Google ad settings and can control cookies through your browser settings.</p>
      </LegalSection>

      <LegalSection title="How We Use Information">
        <p>We use information to operate the tools, deliver downloads, authenticate users, secure the service, troubleshoot errors, improve features, communicate with users, comply with legal obligations, and prevent fraud or misuse.</p>
      </LegalSection>

      <LegalSection title="Third-Party Services">
        <p>We may use service providers for hosting, authentication, analytics, email, storage, security, and advertising. These providers process information as needed to deliver their services to MyConverterTool.</p>
      </LegalSection>

      <LegalSection title="Contact">
        <p>For privacy questions, contact us at <a className="text-blue-600 font-bold" href="mailto:admin@myconvertertool.com">admin@myconvertertool.com</a>.</p>
      </LegalSection>

      <p className="mt-10 text-sm text-slate-500">Last updated: June 27, 2026</p>
    </div>
  );
};

const LegalHeader = ({ title, subtitle }) => (
  <section className="text-center py-16 md:py-24">
    <h1 className="text-4xl md:text-6xl font-black tracking-tight mb-6">{title}</h1>
    <p className="text-lg text-slate-600 dark:text-slate-400 max-w-3xl mx-auto">{subtitle}</p>
  </section>
);

const LegalSection = ({ title, children }) => (
  <section className="max-w-4xl mx-auto mb-10 rounded-2xl border border-slate-200 dark:border-slate-800 p-6 md:p-8 bg-white/70 dark:bg-slate-900/40">
    <h2 className="text-2xl font-black mb-4 text-slate-900 dark:text-white">{title}</h2>
    <div className="space-y-4 text-slate-600 dark:text-slate-400 leading-relaxed">{children}</div>
  </section>
);

LegalHeader.propTypes = {
  title: PropTypes.string.isRequired,
  subtitle: PropTypes.string.isRequired,
};

LegalSection.propTypes = {
  title: PropTypes.string.isRequired,
  children: PropTypes.node.isRequired,
};

export default PrivacyPolicy;
