import { PDFDocument, rgb } from 'pdf-lib';
import fs from 'fs';
import path from 'path';
import { exec } from 'child_process';
import { cleanupFiles } from './fileUtils.js';

// Helper Function: Convert Image(s) to PDF
export const convertImagesToPDF = async (imagePaths) => {
  const pdfDoc = await PDFDocument.create();
  const imagePathsArray = Array.isArray(imagePaths) ? imagePaths : [imagePaths];

  for (const imagePath of imagePathsArray) {
    const imageBytes = fs.readFileSync(imagePath);
    const extension = path.extname(imagePath).toLowerCase();

    const image = extension === ".png"
      ? await pdfDoc.embedPng(imageBytes)
      : await pdfDoc.embedJpg(imageBytes);

    const page = pdfDoc.addPage([image.width, image.height]);
    page.drawImage(image, {
      x: 0,
      y: 0,
      width: image.width,
      height: image.height,
    });
  }

  return Buffer.from(await pdfDoc.save());
};

// PDF Conversion Functions with libreoffice
const getLibreOfficePath = () => {
  if (process.env.LIBREOFFICE_PATH) {
    return process.env.LIBREOFFICE_PATH;
  }

  // Platform-specific default paths
  switch (process.platform) {
    case "win32": // Windows
      return "C:\\Program Files\\LibreOffice\\program\\soffice.exe";
    case "darwin": // macOS
      return "/Applications/LibreOffice.app/Contents/MacOS/soffice";
    case "linux":
    default:
      return "/usr/bin/soffice";
  }
};

const libreOfficePath = getLibreOfficePath();

if (!fs.existsSync(libreOfficePath)) {
  console.error(`❌ LibreOffice executable not found at: ${libreOfficePath}`);
  console.error("Please ensure LibreOffice is installed and its path is correctly configured in .env or is in a standard location.");
  process.exit(1); // Stop execution if the executable is missing
} else {
  console.log("✅ LibreOffice Path:", libreOfficePath);
}

// Convert a single file to PDF using LibreOffice
const convertToPDF = (inputPath) => {
  return new Promise((resolve, reject) => {
    const outputDir = path.dirname(inputPath);
    const command = `"${libreOfficePath}" --headless --convert-to pdf --outdir "${outputDir}" "${inputPath}"`;

    exec(command, (error, stdout, stderr) => {
      if (error) {
        console.error("❌ LibreOffice Conversion Error:", stderr);
        return reject("LibreOffice failed to convert the file.");
      }

      console.log("📄 LibreOffice Output:", stdout);

      // Find the generated PDF file in the output directory
      const files = fs.readdirSync(outputDir);
      const pdfFile = files.find(
        (file) =>
          file.endsWith(".pdf") &&
          file.includes(path.basename(inputPath, path.extname(inputPath)))
      );

      if (!pdfFile) {
        console.error("❌ PDF file was not created.");
        return reject("Conversion failed: No output file.");
      }

      const generatedPdfPath = path.join(outputDir, pdfFile);
      console.log(`✅ PDF Successfully Created: ${generatedPdfPath}`);

      if (!fs.existsSync(generatedPdfPath)) {
        return reject("File conversion failed: PDF file not found.");
      }

      resolve(generatedPdfPath);
    });
  });
};

// Helper Function: Convert Files to PDF for Batch Mode
export const convertFileToPDF = async (filePath, fileType) => {
  const supportedImageTypes = ["png", "jpg", "jpeg"];
  const supportedLibreOfficeTypes = ["md", "docx", "pptx", "xlsx", "odt", "ods", "odp", "txt"];

  if (supportedImageTypes.includes(fileType)) {
    // convertImagesToPDF expects an array, so wrap filePath in an array
    return await convertImagesToPDF([filePath]);
  } else if (supportedLibreOfficeTypes.includes(fileType)) {
    const pdfPath = await convertToPDF(filePath);
    const pdfBuffer = fs.readFileSync(pdfPath);
    await fs.promises.unlink(pdfPath); // Clean up the temporary PDF generated by LibreOffice asynchronously
    return pdfBuffer;
  } else {
    throw new Error(`Unsupported file type for batch conversion: ${fileType}`);
  }
};

// Process conversion for one or more files
export const processFileConversion = async (files) => {
  const convertedResults = [];

  for (const file of files) {
    try {
      const extension = path.extname(file.originalname).toLowerCase().replace(".", "");
      const pdfBuffer = await convertFileToPDF(file.path, extension);
      convertedResults.push({
        filename: file.originalname.replace(/\.[^/.]+$/, "") + ".pdf",
        base64: Buffer.from(pdfBuffer).toString("base64"),
        temp: file.path, // Keep original temp path for cleanup
        convertedTemp: null // Will be set if convertFileToPDF returns a path
      });
    } catch (error) {
      console.error(`❌ Error converting ${file.originalname}:`, error);
      // Optionally, push an error result or skip this file
    }
  }

  // Cleanup original uploaded files
  cleanupFiles(files.map(file => file.path));

  return convertedResults;
};